# Generated by Django 4.1.3 on 2022-12-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_date_question_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
    ]
