# Generated by Django 4.1.3 on 2023-01-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_avatar_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteanswer',
            name='is_like',
        ),
        migrations.RemoveField(
            model_name='votequestion',
            name='is_like',
        ),
    ]
